### ISSUE TITLE
0.8.9 -> 0.9.0 Migration Guide documentation 

### ISSUE THREAD

**Issue by alphatownsman** [neodb-social/neodb#397]
_see #48 if you are on 0.4.x or earlier_

0. Upgrade to 0.8.9 if not yet; ensure you have enough disk space for database which may grow ~200% or more

1. generate unique usernames for every row in users_user
```
python manage.py generate_usernames
```

2. Get docker compose ready. Write configuration in `.env`, make sure env var for database/redis/typesense/data/email/scraper proxy/api key/etc are all set

3. Create blank database for takahe if not yet

4. add these lines to `.env`, and remember to remove them after migration
```
NEODB_DISABLE_CRON=True
NEODB_FANOUT_LIMIT_DAYS=64
TAKAHE_FANOUT_LIMIT_DAYS=64
TAKAHE_STATOR_CONCURRENCY=64
TAKAHE_STATOR_CONCURRENCY_PER_MODEL=64
```

5. run next few steps in `docker compose --profile production run shell`
```
takahe-manage migrate
neodb-manage migrate 
neodb-manage check --database default --database takahe --deploy
```
in case a faulty beta of `django-auditlog` was installed earlier:
```
alter table auditlog_logentry add column changes_text text null default null;
```
6. start takahe background job to finish user relationship creation
```
docker compose --profile production up takake-stator -d
```

7. add temporary index
```
$ docker compose run shell takahe-manage dbshell

takahe=> create index tmp_post_published on activities_post(local, published);
CREATE INDEX
```

8. rebuild posts and likes, in `docker compose --profile production run shell` run 
```
neodb-manage backfill_takahe --post 
neodb-manage backfill_takahe --timeline 
neodb-manage backfill_takahe --like 
```
add `--csv` to use csv mode, then load csv in psql directly
```
COPY activities_timelineevent (type,identity_id,subject_post_id,subject_identity_id,published,created,seen,dismissed) FROM '/tmp/t.csv' DELIMITER ',' CSV HEADER;
```
if there are duplicated data in timeline:
```
DELETE FROM activities_timelineevent t1
USING activities_timelineevent t2
WHERE t1.type= 'post' AND t2.type = 'post'
AND t1.identity_id = t2.identity_id 
AND t1.subject_post_id = t2.subject_post_id 
AND t1.subject_identity_id = t2.subject_identity_id
AND t1.id < t2.id ;
```

9. remove temporary index
```
$ docker compose run shell takahe-manage dbshell

takahe=> drop index tmp_post_published;
DROP INDEX
```

10. undo step 4, remove temporary values in `.env`

11. refresh internal stats otherwise instance info API will be very slow; consider turn on auto vacuum option in psql as well.
```
vacuum analyze ;
```

12. start server
```
docker compose --profile production up -d
```
---
use docker compose with database directly on host with `compose.override.yml` and `.env` below

`compose.override.yml`
```
services:
  redis:
    profiles: ['disabled']
  typesense:
    profiles: ['disabled']
  neodb-db:
    profiles: ['disabled']
  takahe-db:
    profiles: ['disabled']
  migration:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on: !reset []
  neodb-web:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on: !reset []
  neodb-worker:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on: !reset []
  neodb-worker-extra:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on: !reset []
  takahe-web:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on: !reset []
  takahe-stator:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on: !reset []
  shell:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on: !reset []
  root:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on: !reset []
  dev-neodb-web:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on: !reset []
  dev-neodb-worker:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on: !reset []
  dev-takahe-web:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on: !reset []
  dev-takahe-stator:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on: !reset []
  dev-shell:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on: !reset []
  dev-root:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on: !reset []
```

`.env`
```
NEODB_DB_URL=postgres://neodb:xxx@host.docker.internal/neodb
TAKAHE_DB_URL=postgres://takahe:xxx@host.docker.internal/takahe
NEODB_REDIS_URL=redis://host.docker.internal:6379/0
NEODB_SEARCH_URL=typesense://user:xxx@host.docker.internal:8108/catalog
TAKAHE_DATABASE_SERVER=postgres://takahe:xxx@host.docker.internal/takahe
TAKAHE_CACHES_DEFAULT=redis://host.docker.internal:6379/0
```
